/**
 * Tag Utilities
 * V6.6: Helper functions for tag management
 */

/**
 * V6.6: Merge session tags with AI tags using case-insensitive deduplication.
 * Session tags take precedence (appear first, their casing is preserved).
 * 
 * @param sessionTags - Tags from the session (user-selected)
 * @param aiTags - Tags generated by AI
 * @returns Merged array with no case-insensitive duplicates
 */
export function mergeTagsWithDeduplication(
  sessionTags: string[],
  aiTags: string[]
): string[] {
  const result: string[] = []
  const seenLower = new Set<string>()
  
  // Add session tags first (they take precedence)
  for (const tag of sessionTags) {
    const trimmed = tag.trim()
    if (trimmed && !seenLower.has(trimmed.toLowerCase())) {
      seenLower.add(trimmed.toLowerCase())
      result.push(trimmed)
    }
  }
  
  // Add AI tags that aren't duplicates
  for (const tag of aiTags) {
    const trimmed = tag.trim()
    if (trimmed && !seenLower.has(trimmed.toLowerCase())) {
      seenLower.add(trimmed.toLowerCase())
      result.push(trimmed)
    }
  }
  
  return result
}

/**
 * V6.6: Check if two tag arrays have any case-insensitive duplicates.
 * 
 * @param tags1 - First tag array
 * @param tags2 - Second tag array
 * @returns True if there are duplicates between the arrays
 */
export function hasTagDuplicates(tags1: string[], tags2: string[]): boolean {
  const lowerTags1 = new Set(tags1.map(t => t.trim().toLowerCase()))
  
  for (const tag of tags2) {
    if (lowerTags1.has(tag.trim().toLowerCase())) {
      return true
    }
  }
  
  return false
}
